"""add bad recipe slug table

Revision ID: b404b6ae09b0
Revises: ea2dbaa664be
Create Date: 2025-01-01 13:43:44.312342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b404b6ae09b0"
down_revision: Union[str, None] = "ea2dbaa664be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bad_recipe_slug",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bad_recipe_slug_slug"), "bad_recipe_slug", ["slug"], unique=False
    )
    op.drop_constraint(
        "instruction_step_recipe_id_fkey", "instruction_step", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "instruction_step", "recipe", ["recipe_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "recipe_ingredient_link_recipe_id_fkey",
        "recipe_ingredient_link",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "recipe_ingredient_link",
        "recipe",
        ["recipe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipe_ingredient_link", type_="foreignkey")
    op.create_foreign_key(
        "recipe_ingredient_link_recipe_id_fkey",
        "recipe_ingredient_link",
        "recipe",
        ["recipe_id"],
        ["id"],
    )
    op.drop_constraint(None, "instruction_step", type_="foreignkey")
    op.create_foreign_key(
        "instruction_step_recipe_id_fkey",
        "instruction_step",
        "recipe",
        ["recipe_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_bad_recipe_slug_slug"), table_name="bad_recipe_slug")
    op.drop_table("bad_recipe_slug")
    # ### end Alembic commands ###
